Repository bitcamp-aiaas-9/MonoRecipe, pull requests merged in 2024-10, with the labels that each got.

#7 fix: index
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/image/apple.jpg
  src/main/webapp/WEB-INF/image/buang.jpg
  src/main/webapp/index.jsp
Labels: client

#8 수정
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/index.jsp
Labels: client

#10 .git ignore 수정
  .gitignore
  src/main/resources/spring/naver.properties
Labels: documentation

#12 <footer>, NCP file, pom dependency, dish package 영역 구분
  pom.xml
  src/main/java/admin/dao/AdminDAO.java
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/com/controller/MonoRecipe/MainController.java
  src/main/java/dish/bean/DishDTO.java
  src/main/java/dish/bean/DishPaging.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/ObjectStorageService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/java/dish/service/impl/NCPObjectStorageService.java
  src/main/java/review/dao/ReviewDAO.java
  src/main/java/user/dao/UserDAO.java
  src/main/resources/sql/dish_tb.sql
  src/main/resources/sql/favorite_tb.sql
  src/main/webapp/WEB-INF/common/footer.jsp
  src/main/webapp/WEB-INF/css/footer.css
  src/main/webapp/WEB-INF/css/init.css
  src/main/webapp/WEB-INF/image/apple.jpg
  src/main/webapp/WEB-INF/image/appstore_icon.png
  src/main/webapp/WEB-INF/image/buang.jpg
  src/main/webapp/WEB-INF/image/lab_icon.png
  src/main/webapp/WEB-INF/image/playstore_icon.png
  src/main/webapp/WEB-INF/image/tomato.png
  src/main/webapp/WEB-INF/image/youtube_icon.png
  src/main/webapp/index.jsp
Labels: bug, documentation, client

#13 add spring folder
  src/main/resources/spring/temp.txt
Labels: documentation

#15 index footer 다시추가
  src/main/webapp/index.jsp
Labels: conflict

#18 fix: .gitignore, add: *.properties
  .gitignore
  src/main/resources/spring/db.properties
  src/main/resources/spring/naver.properties
Labels: documentation

#19 Dev ms/관리자 기능(레시피 등록/삭제/수정)/레시피 등록 수정 페이지
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/css/dishUpdate.css
  src/main/webapp/WEB-INF/css/dishWrite.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishWrite.js
Labels: client, server

#20 ajax로 변경
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishWrite.js
Labels: enhancement, client

#21 <header>, <footer> 수정
  Servers/.settings/org.eclipse.wst.server.core.prefs
  src/main/resources/sql/user_tb.sql
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/css/footer.css
  src/main/webapp/WEB-INF/css/header.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/index.jsp
Labels: bug, client

#22 제품 상세페이지 html
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishView.js
Labels: client

#23 index, header 반응형 완성
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/webapp/WEB-INF/common/footer.jsp
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/css/footer.css
  src/main/webapp/WEB-INF/css/header.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/image/carouselImg1.png
  src/main/webapp/WEB-INF/image/carouselImg2.png
  src/main/webapp/WEB-INF/image/carouselImg3.png
  src/main/webapp/WEB-INF/image/search_icon_black.png
  src/main/webapp/WEB-INF/js/header.js
  src/main/webapp/WEB-INF/js/index.js
  src/main/webapp/index.jsp
Labels: client

#24 레시피 수정 부분 수정/프론트 수정
  .classpath
  .settings/org.eclipse.jdt.core.prefs
  pom.xml
  src/main/java/com/controller/MonoRecipe/UserController.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/java/user/bean/UserDTO.java
  src/main/java/user/dao/UserDAO.java
  src/main/java/user/service/UserService.java
  src/main/java/user/service/impl/UserServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/resources/mapper/userMapper.xml
  src/main/webapp/WEB-INF/css/dishUpdate.css
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/css/dishWrite.css
  src/main/webapp/WEB-INF/css/userSignUp.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/userSignUp.js
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/user/userSignIn.jsp
  src/main/webapp/WEB-INF/user/userSignUp.jsp
  src/main/webapp/WEB-INF/user/userUpdate.jsp
Labels: client, server

#26 부트 스트랩 적용해보기
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/css/dishUpdate.css
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/css/dishWrite.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
Labels: client

#27 유효성 검사 추가
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/dishWrite.js
Labels: client

#28 index.jsp 이동
  .classpath
  .settings/org.eclipse.jdt.core.prefs
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/com/controller/MonoRecipe/MainController.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/index.jsp
Labels: bug

#30 dishView 에서 리뷰작성 리뷰 리스트 잡아둠(아이디 값은 세션으로 받아야하기에 나중에 수정해야함)
  src/main/java/com/controller/MonoRecipe/ReviewController.java
  src/main/java/review/bean/ReviewDTO.java
  src/main/java/review/dao/ReviewDAO.java
  src/main/java/review/service/ReviewService.java
  src/main/java/review/service/impl/ReviewServiceImpl.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishView.js
Labels: server

#33 index, dishList, pom.xml
  Servers/.settings/org.eclipse.wst.server.core.prefs
  pom.xml
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/com/controller/MonoRecipe/MainController.java
  src/main/java/dish/bean/DishPaging.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/css/dishList.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/index.js
Labels: client, server

#35 인덱스,회원기능
  src/main/java/com/controller/MonoRecipe/UserController.java
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/index.jsp
Labels: enhancement

#36 리뷰 삭제/수정+유효성검사 코드개선요청 추가+리스크 목록 이동
  src/main/java/com/controller/MonoRecipe/ReviewController.java
  src/main/java/review/dao/ReviewDAO.java
  src/main/java/review/service/ReviewService.java
  src/main/java/review/service/impl/ReviewServiceImpl.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/css/dishWrite.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/dishWrite.js
Labels: enhancement, client, server

#37 코드개선요청 완료
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/dish/dishWrite.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/dishWrite.js
Labels: enhancement, client

#38 dishList.jsp 관리자 선택 삭제 완성 / dishView.jsp 수정 & 삭제 띄어쓰기
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/ObjectStorageService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/java/dish/service/impl/NCPObjectStorageService.java
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/css/dishList.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishList.js
Labels: bug, client, server

#41 dishView.jsp, dishUpdate.jsp css 조정, dscore 리뷰 삭제 시 업데이트 트리거 추가
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/resources/sql/dish_tb.sql
  src/main/webapp/WEB-INF/css/dishUpdate.css
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
Labels: client

#42 리뷰 버튼/수정삭제 버튼 히든 처리
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: enhancement, client

#43 리뷰 수정 별점 변경
  src/main/webapp/WEB-INF/js/dishView.js
Labels: enhancement, client

#44 review_tb 트리거 재생성, 헤더 수정
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/resources/sql/dish_tb.sql
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/user/userList.jsp
  src/main/webapp/WEB-INF/user/userMyPage.jsp
Labels: bug

#47 dishList.jsp checkbox 수정
  src/main/webapp/WEB-INF/css/dishList.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
Labels: client

#49 검색 기능
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/dish/bean/DishPaging.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/js/dishList.js
Labels: enhancement, client, server

#53 검색기능 수정/하트추가
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: enhancement, client

#55 css js 수정
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
Labels: enhancement, client

#58 이름 없음음 변경/메인페이지 검색
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/index.js
Labels: enhancement, client

#59 검색기능 개선
  src/main/webapp/WEB-INF/js/dishList.js
Labels: enhancement

#61 헤더수정, userMyPage 작업중
  src/main/java/com/controller/MonoRecipe/UserController.java
  src/main/resources/sql/dish_tb.sql
  src/main/resources/sql/favorite_tb.sql
  src/main/resources/sql/review_tb.sql
  src/main/resources/sql/user_tb.sql
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/common/myPageMenu.jsp
  src/main/webapp/WEB-INF/css/dishList.css
  src/main/webapp/WEB-INF/css/myPageMenu.css
  src/main/webapp/WEB-INF/css/userMyPage.css
  src/main/webapp/WEB-INF/js/userMyPage.js
  src/main/webapp/WEB-INF/user/userMyPage.jsp
Labels: documentation, client

#62 프론트 수정
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
Labels: client

#63 #mobileMenuList 수정
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/css/header.css
  src/main/webapp/WEB-INF/js/header.js
Labels: client

#71 헤더 검색칸 css
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/css/header.css
  src/main/webapp/WEB-INF/image/close_icon_black.png
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/js/header.js
Labels: client

#73 View 즐겨찾기 저장/삭제/확인
  src/main/java/com/controller/MonoRecipe/favoriteController.java
  src/main/java/favorite/bean/FavoriteDTO.java
  src/main/java/favorite/dao/FavoriteDAO.java
  src/main/java/favorite/service/FavoriteService.java
  src/main/java/favorite/service/impl/FavoriteServiceImpl.java
  src/main/java/spring/conf/SpringConfiguration.java
  src/main/resources/mapper/favoriteMapper.xml
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/spring/root-context.xml
Labels: enhancement, client, server

#79 즐겨찾기 목록 조회 기능
  src/main/java/com/controller/MonoRecipe/FavoriteController.java
  src/main/java/com/controller/MonoRecipe/MainController.java
  src/main/java/com/controller/MonoRecipe/UserController.java
  src/main/java/favorite/dao/FavoriteDAO.java
  src/main/java/favorite/service/FavoriteService.java
  src/main/java/favorite/service/impl/FavoriteServiceImpl.java
  src/main/resources/mapper/favoriteMapper.xml
  src/main/resources/sql/dish_tb.sql
  src/main/webapp/WEB-INF/js/dishView.js
  src/main/webapp/WEB-INF/js/userMyPage.js
  src/main/webapp/WEB-INF/user/userMyPage.jsp
Labels: server

#84 즐겨찾기 목록 선택 삭제 구현
  src/main/java/com/controller/MonoRecipe/DishController.java
  src/main/java/com/controller/MonoRecipe/FavoriteController.java
  src/main/java/com/controller/MonoRecipe/UserController.java
  src/main/java/dish/dao/DishDAO.java
  src/main/java/dish/service/DishService.java
  src/main/java/dish/service/impl/DishServiceImpl.java
  src/main/java/favorite/dao/FavoriteDAO.java
  src/main/java/favorite/service/FavoriteService.java
  src/main/java/favorite/service/impl/FavoriteServiceImpl.java
  src/main/resources/mapper/dishMapper.xml
  src/main/resources/mapper/favoriteMapper.xml
  src/main/resources/sql/dish_tb.sql
  src/main/webapp/WEB-INF/css/dishList.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/userMyPage.css
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/js/userMyPage.js
  src/main/webapp/WEB-INF/user/userMyPage.jsp
Labels: bug, client, server

#85 검색 해결
  src/main/webapp/WEB-INF/common/header.jsp
  src/main/webapp/WEB-INF/css/dishUpdate.css
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/css/header.css
  src/main/webapp/WEB-INF/css/index.css
  src/main/webapp/WEB-INF/css/userSignUp.css
  src/main/webapp/WEB-INF/dish/dishUpdate.jsp
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/header.js
Labels: enhancement, client

#86 코드개선
  src/main/webapp/WEB-INF/css/dishView.css
  src/main/webapp/WEB-INF/dish/dishView.jsp
  src/main/webapp/WEB-INF/js/dishUpdate.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: enhancement, client

#91 검색창 숨기기
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/header.js
  src/main/webapp/WEB-INF/user/userMyPage.jsp
Labels: client

#92 검색 유지한채 뒤로가기 수정 중
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: server

#93 검색 유지한채 뒤로가기 해결
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: server

#94 관리자 검색기능 추가
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/js/dishList.js
Labels: enhancement, client

#95 모바일 검색창 나타날 때 검색아이콘, 메뉴아이콘 밀림 해결
  src/main/webapp/WEB-INF/css/header.css
Labels: client

#96 dishList 검색어 없을 때 무한 로딩 해결
  src/main/webapp/WEB-INF/index.jsp
  src/main/webapp/WEB-INF/js/dishList.js
  src/main/webapp/WEB-INF/js/dishView.js
Labels: bug

#98 관리자 검색기능 개선
  src/main/webapp/WEB-INF/dish/dishList.jsp
  src/main/webapp/WEB-INF/js/dishList.js
Labels: client

#100 네이버 로그인 이미지 추가 image/naverLoginImg.png
  src/main/webapp/WEB-INF/image/naverLoginImg.png
Labels: client

#101 탈퇴 팝업 버튼 가로 조정
  src/main/webapp/WEB-INF/css/userSignUp.css
Labels: client

#104 favorite 매핑
  src/main/java/com/controller/MonoRecipe/FavoriteController.java
  src/main/webapp/WEB-INF/js/dishView.js
Labels: bug

#105 admin id display: none;
  src/main/webapp/WEB-INF/dish/dishList.jsp
Labels: bug
